### ISSUE TITLE
Exporting frontend translations only

### ISSUE THREAD

**Issue by brendanfalkowski** [tzyganu/MagentoTranslationTool#2]
Is it possible to ignore all translations for the admin while exporting?

Trying to get a list of strings from PHTML, XML, and error messages returned to the frontend only.

**Comment by tzyganu** [comment]
@brendanfalkowski you can configure any record you want parsed to include only specific files and folders, or exclude specific files  See the [How it works section](https://github.com/tzyganu/MagentoTranslationTool#how-to-use).  All these configurations are stored in the table `translate_module`. You can parse the included files and remove anything related to frontend.

**Comment by brendanfalkowski** [comment]
@tzyganu Saw that — wondered if there was an easy modification to exclude all `adminhtml` folders from all modules.

I can work through configuring each one. Will still save a lot of time collecting all the strings. Thanks!
