### ISSUE TITLE
Permission denied to write to ../app/local/

### ISSUE THREAD

**Issue by MMB1983** [tzyganu/MagentoTranslationTool#5]
I wanted to test this extension on Magento CE 1.9.1 and it gives this error : "Permission denied to write to ../app/local/" when I want to Generate Local Files.

**Comment by tzyganu** [comment]
@mastakilla1983 That's odd. The extension should not write to `app/local`. It should write to `var/translation`. But I'll take a look and try to reproduce it.  
Could you help me with the steps you follow in order to get to that error?

**Comment by MMB1983** [comment]
Hi, thanks for quick reply,

Ok when I go to : System>Tools>Translations>Operations>
Than I choose: "Generate Locale files"
In "Locale Code" I typed many different folders (one each time)
I assume that the path to custom translate.csv file in "
app/design/frontend/default/sns_nova/locale/pl_PL"
I also tried "app/locale/en_US" or "/app/locale/pl_PL" where all
translation files
are
Or "/app/code/local/Sns/Nova"

Each time I have tried something different I still have the same result.
Maybe I do it wrong

Also This extension does not see any local modules and only two in
community pool.

I have just noticed that each time I clicked Folder with translation files
was generated in "var/translations"
Each of this folder contains the exactly the same files.
I also noticed that when I didn't type anything in "Locale Code" the huge
over 20Gb tar file was generated in that field.

How to actually generate csv file of any module which does not have any
translation?
Also why no other "Local" and "Community"modules are not visible in "Custom
Module" filter

Thanks
Marcin

**Comment by MMB1983** [comment]
Hi again,

I partially sorted this out. I was typing the whole path and mostly wrong.
Now when I type "en_US" everything is ok. I had system info log with message

2015-10-29T14:13:54+00:00 ERR (3): Warning:
opendir(app/locale/app/code/local/Sns/Nova/): failed to open dir: No such
file or directory  in
/users/0023/sh182964/www/vapex-3.03/includes/src/Easylife_Translation_Model_Handler.php
on line 481

But still no other "Local" and "Community"modules are listed.
Kind Regards
Marcin

**Comment by tzyganu** [comment]
@mastakilla1983  Not all installed modules are parsed. You need to declare the modules you want parsed.  
For this see the [How to Use section](https://github.com/tzyganu/MagentoTranslationTool#how-to-use) the "Modules" part.  
You need to add your modules in a list. 

I will close this issue now.

**Comment by MMB1983** [comment]
Hi,

Thanks for help
Kind Regards
Marcin
